name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ develop ]
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: Sandbox

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    #caches maven dependencies
    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    #setup java 1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Publish to Exchange
      run: |
        mvn deploy --settings .maven/settings.xml -DskipMunitTests \
        -DconnectedApp.clientId="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
        -DconnectedApp.clientSecret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
        -DconnectedApp.clientId=${{ secrets.CONNECTED_APP_CLIENT_ID }} \
        -DconnectedApp.clientSecret=${{ secrets.CONNECTED_APP_CLIENT_SECRET }} \
        -Dmule.env=dev \
        -Danypoint.platform.client_id=${{ secrets.AP_CLIENTID }} \
        -Danypoint.platform.client_secret=${{ secrets.AP_CLIENTSECRET }} 